### ISSUE TITLE
 CreateUHostInstanceRequest 定义缺少指定 CPU 型号参数

### ISSUE THREAD

**Issue by souxls** [ucloud/ucloud-sdk-go#203]
在 CreateUHostInstanceRequest struct 的定义中没有 CpuPlatform这个参数，在使用CreateUHostInstance创建主机的时候不能指定具体型号，只能使用默认 CPU 型号 Intel，不能使用 Amd。

**Comment by shawnmssu** [comment]
有定义 CPU 型号的参数`MinimalCpuPlatform`：

**Comment by souxls** [comment]
> 
> 
> 有定义 CPU 型号的参数 `MinimalCpuPlatform`，可以更新到最新的版本使用一下：
> 
>     * [代码链接](https://github.com/ucloud/ucloud-sdk-go/blob/master/services/uhost/apis.go#L350)
> 
>     * [型号参考](https://docs.ucloud.cn/uhost/introduction/uhost/type_new?id=cpu%e5%b9%b3%e5%8f%b0)

哦哦，好的。多谢。看到文档里面枚举类型只有Intel的，我以为是要和 CpuPlatform 这个配合使用呢。

**Comment by shawnmssu** [comment]
> > 有定义 CPU 型号的参数 `MinimalCpuPlatform`，可以更新到最新的版本使用一下：
> > ```
> > * [代码链接](https://github.com/ucloud/ucloud-sdk-go/blob/master/services/uhost/apis.go#L350)
> > 
> > * [型号参考](https://docs.ucloud.cn/uhost/introduction/uhost/type_new?id=cpu%e5%b9%b3%e5%8f%b0)
> > ```
> 
> 哦哦，好的。多谢。看到文档里面枚举类型只有Intel的，我以为是要和 CpuPlatform 这个配合使用呢。

好的，回头我们更新一下文档，以免造成不必要的误导，多谢反馈

**Comment by souxls** [comment]
MinimalCpuPlatform = "Amd/epyc2"
