### ISSUE TITLE
签名计算方法 

### ISSUE THREAD

**Issue by chowyu08** [ucloud/ucloud-sdk-go#65]
我看了一下，ucloud的签名计算方法，代码上有一点我有疑问，
https://github.com/ucloud/ucloud-sdk-go/blob/master/ucloud/auth/credential.go#L30

如果publicKey里面有= 怎么办？

**Comment by yufeiminds** [comment]
Hi，@chowyu08 

你好，很高兴收到反馈。

CreateSign 方法期望传入 URL Encoded 字符串，所以 PublicKey 应该在传进来的时候就被 Encode 过了，所以不应该有 `=`。

比如在这一行代码中
https://github.com/ucloud/ucloud-sdk-go/blob/master/ucloud/auth/credential.go#L49

PublicKey 就是 Encode 之后传给了 CreateSign

**Comment by chowyu08** [comment]
好的，谢谢
