### ISSUE TITLE
数组型参数签名计算

### ISSUE THREAD

**Issue by chowyu08** [ucloud/ucloud-sdk-go#68]
我看了一下 SDK的签名计算方法 https://github.com/ucloud/ucloud-sdk-go/blob/master/ucloud/auth/credential.go#L44

想请问一下数组型参数签名怎么计算？

**Comment by chowyu08** [comment]
我有一个测试的工程，当数组长度小于10 计算是OK，当数组长度大于10 计算错误返回170

**Comment by yufeiminds** [comment]
Hello, @chowyu08 

感谢，已收到反馈，我们尝试复现一下。

数组参数我们会序列化为扁平的协议由产品侧服务解析，例如 `[]Disks{{Size: 10}}` => `Disks.0.Size=10`，签名根据序列化之后的参数计算。

您可以提供一下接口和参数的详细信息吗？这样可以帮助我们排查问题

Best Regards
UCloud Team
